language: ruby

rvm:
 - 2.3.0

script:
 - bundle exec rake db:migrate --trace
 - RAILS_ENV=test bundle exec rake db:migrate --trace
 - bundle exec rake db:test:prepare
 - bundle exec rspec -fd spec
 - bundle exec cucumber

deploy:
  provider: heroku
  api_key:
    secure: "vpBfCUuoq7XJVyktHicqLrZREEIIF0DXeOxNAnFbceoyC4+Mm34ZszkBEe/ReElgiCwSvTzuT37SiQgAtN3PQ5buI1emkArOqHXpbuMoDLoJ9QGM0aDx//u5QRnH5YQ+DYEJ5ol2yO6N9YT9hF/n5hzwU2kdlonpRljql+I8zuY1DjzmyljTJN1ZphSnfwCfoPPcWMwlS4WQdX5a/fgaHa1yrhGF6mc8LyGczfKOPBuBdWVRaPec+Ax+yDuIEfGWQRtDDjyrqxeWB6hzxbJB0hZ7uNrp/El0tRIEdiEX/GB1ihogWhLGa4OmYGkAnLiZ3aUBkALbZ5qksX00dTxRjMTuSy35lOE2peg+Nb5VlQztzTZFuFreyzakisgiqSdMvWNvx0Uy1nOAKAfulEB3vGh3De3ddR5lCRVRBeZ4NmJFx69t63gjzJKwpYdhm5Y6NJScke6KGaN/OoQdUAyZ+JFUxXVHNxK3293aVdrOKrlWMJIoRrXGlBLmQ/lUm8mL9CLAe43O63DZB+3l/r7vt83ohNNAVWmX5atL663A42L6eOWG6TFXzY8yK1wbedDORYFkl6VSylbGxsTO/PiePKx567HqWq6Os7GVNdHsByGNux1cLf0Af/2/g7EoEpePXcHkjAgJwdyzx/dBjglduMVMrWb6bteekq9OLjaJnGo="
  app: viittaaja
  run: "rake db:migrate"
